### ISSUE TITLE
GPU based TI calculations

### ISSUE THREAD

**Issue by DDGmichigan** [linfranksong/Input_TI#1]
Hi,
I am trying to setup AMBER18 GPU based TI calculations using the protocol mentioned in your paper,
However, I am a bit confused as to why would you need to equilibrate at lambda=0.5 and use that as starting structures for TI on 12 different lambdas?

Can you explain that a bit as mentioned in page 3130 of the JCIM paper..

**Comment by linfranksong** [comment]
Hi,
At the time I performed the calculations, the NPT equilibration of GPU TI is not available, so I had to use the CPU version. To save time, instead of equilibrating at each lambda, I equilibrated the density at lambda=0.5, and use that structure for TI on the 12 lambdas. This protocol may not be the best. I'd suggest you either do your calculations sequentially for the 12 lambdas, or if you want to do it in parallel, you can minimize/heat/equilibrate at each of the 12 lambdas.

Best,
Lin

**Comment by DDGmichigan** [comment]
So for the publication did you report results on TI done on GPU or conventional TI on cpus?
Thanks


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by linfranksong** [comment]
The NPT equilibration at lambda=0.5 was done by CPU TI. After that, the TI calculations at each lambda was in GPU. It was mentioned in the method part.

**Comment by DDGmichigan** [comment]
Thanks.
Is it okay if I contact you when encountering some issues related to the step?

Thanks
Regards


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by linfranksong** [comment]
Sure. No problem!

**Comment by DDGmichigan** [comment]
Hi Lin,

wishing you a  very Happy new Year 2020.

I was wondering can you kindly explain why you chose NVT simulation for 12 lambda windows for collecting Du/Dlambda and not NPT simulation?

what is the logic in that?

**Comment by linfranksong** [comment]
Hi,

At the time of my calculation, NPT GPU TI simulation has some problem.

Best,
Lin
On Jan 7, 2020, at 11:57 AM, DDGmichigan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lin,

wishing you a very Happy new Year 2020.

I was wondering can you kindly explain why you chose NVT simulation for 12 lambda windows for collecting Du/Dlambda and not NPT simulation?

what is the logic in that?

**Comment by DDGmichigan** [comment]
Hi Lin,
So, after running productions(NVT) for 10ns at each of the 12 lambd values, would you explain how to analyse the results? Do you have any script which I may use to analyse the output files generated. I am very grateful for the help extended by you.
Thanks

**Comment by linfranksong** [comment]
Hi,

At the end of the production runs, the average DV/DL will be printed out. You can collect them with a script, and then use different weighting factors for the 12 windows to get the free energy change.

Best,
Lin

On Jan 8, 2020, at 11:36 AM, DDGmichigan <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Lin,
So, after running productions(NVT) for 10ns at each of the 12 lambd values, would you explain how to analyse the results? Do you have any script which I may use to analyse the output files generated. I am very grateful for the help extended by you.
Thanks

**Comment by DDGmichigan** [comment]
So if one uses more than 12 windows how will I get the weights?
The manual speaks of a maximum of 12 windows...also how was the overall MUE calculated in the paper?
Thanks!

**Comment by linfranksong** [comment]
The weights are from gaussian quadrature. I just found a webpage that has the weights but you can verify it: https://pomax.github.io/bezierinfo/legendre-gauss.html.

There is no need to have window more than 12. 12 is more than enough.

MUE was calculated comparing to the experimental values.


On Jan 8, 2020, at 12:34 PM, DDGmichigan <notifications@github.com<mailto:notifications@github.com>> wrote:


So if one uses more than 12 windows how will I get the weights?
The manual speaks of a maximum of 12 windows...also how was the overall MUE calculated in the paper?
Thanks!

**Comment by DDGmichigan** [comment]
Hi Lin, do you think the density hs equilibrated? This is after5ns of NPT equilibration.[cid:image001.png@01D5C62F.564CBD50]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by linfranksong** [comment]
Hi, I can't see anything. You can plot the density versus time. It shouldn't take so long to equilibrate the density.

**Comment by DDGmichigan** [comment]
Would you kindly provide me the email address, as that way If I mail you nay doubts, I can cc my supervisor Prof Carlson, as she may want to be in the loop!
Sorry for the trouble Lin.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by linfranksong** [comment]
No problem. My email is songlin3@msu.edu<mailto:songlin3@msu.edu>

Best,
Lin
On Jan 8, 2020, at 2:52 PM, DDGmichigan <notifications@github.com<mailto:notifications@github.com>> wrote:

Would you kindly provide me the email address, as that way If I mail you nay doubts, I can cc my supervisor Prof Carlson, as she may want to be in the loop!
Sorry for the trouble Lin.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by DDGmichigan** [comment]
![image](https://user-images.githubusercontent.com/48214273/72012271-a9151300-3229-11ea-9af4-a02229c80e1a.png)
