### ISSUE TITLE
Thrombin ligands

### ISSUE THREAD

**Issue by hannahbrucemacdonald** [linfranksong/Input_TI#3]
Hey - The ligand files provided in the thrombin directory don't appear to be the ligands in the original Schrodinger JACS paper, are there some atoms missing? Or is there a reason for this.

Thanks for your help!

Hannah

**Comment by linfranksong** [comment]
Hi Hannah,

The ligands of thrombin can be divided into PHE, PRO and remaining. PHE and PRO are standard amino acids. The files are for the remaining part.

Best,
Lin

On Jan 11, 2020, at 2:15 PM, Hannah Bruce Macdonald <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey - The ligand files provided in the thrombin directory don't appear to be the ligands in the original Schrodinger JACS paper, are there some atoms missing? Or is there a reason for this.

Thanks for your help!

Hannah
